# Generated by Django 4.1.3 on 2022-12-04 18:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=65536)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^(\\+\\d{1,2}\\s)?\\(?\\d{3}\\)?[\\s.-]?\\d{3}[\\s.-]?\\d{4}(?:[\\s.-]?\\d{2,5})?$')])),
                ('address', models.CharField(max_length=128)),
                ('permission', models.CharField(choices=[('ta', 'TA'), ('professor', 'Professor'), ('admin', 'Admin')], default='ta', max_length=16)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LabSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('assignedTA', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='schedulingApp.profile')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='schedulingApp.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseToProfessorEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignedProfessor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='schedulingApp.profile')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='schedulingApp.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseToAssignmentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedulingApp.assignment')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='schedulingApp.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseToAssignedTAEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignedTA', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='schedulingApp.profile')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='schedulingApp.course')),
            ],
        ),
    ]
